'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Themes
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Themes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Telemetry.Themes.Themes", GetType(Themes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;!--Created by exporting the settings of a KryptonPalette instance.--&gt;
        '''&lt;!--For more information about Krypton visit www.ComponentFactory.com--&gt;
        '''&lt;!--WARNING: Modifying this file may render it invalid for importing.--&gt;
        '''&lt;KryptonPalette Version=&quot;18&quot; Generated=&quot;Tuesday, 20 October 2015, 16:34&quot;&gt;
        '''  &lt;Properties&gt;
        '''    &lt;ButtonSpecs&gt;
        '''      &lt;FormClose&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache1&quot; /&gt;
        '''      &lt;/FormClose&gt;
        '''      &lt;FormMin&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache2&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Crimson() As String
            Get
                Return ResourceManager.GetString("Crimson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;!--Created by exporting the settings of a KryptonPalette instance.--&gt;
        '''&lt;!--For more information about Krypton visit www.ComponentFactory.com--&gt;
        '''&lt;!--WARNING: Modifying this file may render it invalid for importing.--&gt;
        '''&lt;KryptonPalette Version=&quot;18&quot; Generated=&quot;Tuesday, 20 October 2015, 16:34&quot;&gt;
        '''  &lt;Properties&gt;
        '''    &lt;ButtonSpecs&gt;
        '''      &lt;FormClose&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache1&quot; /&gt;
        '''      &lt;/FormClose&gt;
        '''      &lt;FormMin&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache2&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Gold() As String
            Get
                Return ResourceManager.GetString("Gold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;!--Created by exporting the settings of a KryptonPalette instance.--&gt;
        '''&lt;!--For more information about Krypton visit www.ComponentFactory.com--&gt;
        '''&lt;!--WARNING: Modifying this file may render it invalid for importing.--&gt;
        '''&lt;KryptonPalette Version=&quot;18&quot; Generated=&quot;Tuesday, 20 October 2015, 16:34&quot;&gt;
        '''  &lt;Properties&gt;
        '''    &lt;ButtonSpecs&gt;
        '''      &lt;FormClose&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache1&quot; /&gt;
        '''      &lt;/FormClose&gt;
        '''      &lt;FormMin&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache2&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property OliveDrab() As String
            Get
                Return ResourceManager.GetString("OliveDrab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;!--Created by exporting the settings of a KryptonPalette instance.--&gt;
        '''&lt;!--For more information about Krypton visit www.ComponentFactory.com--&gt;
        '''&lt;!--WARNING: Modifying this file may render it invalid for importing.--&gt;
        '''&lt;KryptonPalette Version=&quot;18&quot; Generated=&quot;Tuesday, 20 October 2015, 16:34&quot;&gt;
        '''  &lt;Properties&gt;
        '''    &lt;ButtonSpecs&gt;
        '''      &lt;FormClose&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache1&quot; /&gt;
        '''      &lt;/FormClose&gt;
        '''      &lt;FormMin&gt;
        '''        &lt;Image Type=&quot;Image&quot; Value=&quot;ImageCache2&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property RoyalBlue() As String
            Get
                Return ResourceManager.GetString("RoyalBlue", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
